Repository opendistro/for-elasticsearch-docs, pull requests merged in 2020-05, with the labels that each got.

#202 Intro, basic queries, delete, cli, odbc
  docs/images/cli.gif
  docs/images/expression.png
  docs/images/expressionAtom.png
  docs/images/joinPart.png
  docs/images/mac_installer_destination.png
  docs/images/mac_installer_home.png
  docs/images/mac_installer_license.png
  docs/images/mac_installer_password.png
  docs/images/mac_installer_readme.png
  docs/images/mac_installer_select_and_browse.png
  docs/images/mac_installer_succesful.png
  docs/images/mac_signing_error_1.png
  docs/images/mac_signing_error_2.png
  docs/images/predicate.png
  docs/images/selectElement.png
  docs/images/selectElements.png
  docs/images/showFilter.png
  docs/images/showStatement.png
  docs/images/singleDeleteStatement.png
  docs/images/sql.png
  docs/images/tableName.png
  docs/images/tableSource.png
  docs/images/tableau_connection.png
  docs/images/tableau_connection_error.png
  docs/images/tableau_dsn.png
  docs/images/tableau_sample_data.png
  docs/images/tableau_sample_viz.png
  docs/images/windows_dsn_customize.png
  docs/images/windows_installer_home.png
  docs/images/windows_installer_install.png
  docs/images/windows_installer_select_and_browse.png
  docs/images/windows_signing_error_1.png
  docs/images/windows_singing_error_2.png
  docs/images/workbench.gif
  docs/sql/basic.md
  docs/sql/cli.md
  docs/sql/complex.md
  docs/sql/delete.md
  docs/sql/endpoints.md
  docs/sql/functions.md
  docs/sql/index.md
  docs/sql/jdbc.md
  docs/sql/joins.md
  docs/sql/limitation.md
  docs/sql/metadata.md
  docs/sql/monitoring.md
  docs/sql/odbc.md
  docs/sql/operations.md
  docs/sql/partiql.md
  docs/sql/protocol.md
  docs/sql/settings.md
  docs/sql/sql-full-text.md
  docs/sql/troubleshoot.md
  docs/sql/workbench.md
Labels: sql, upcoming release

#205 AD Updated UI
  docs/ad/api.md
  docs/ad/index.md
  docs/alerting/monitors.md
  docs/images/ad.png
Labels: anomaly detection, upcoming release

#228 Adds AMI section
  docs/install/ami.md
Labels: upcoming release, work in progress

#230 Preparing for 1.7.0
  docs/elasticsearch/full-text.md
  docs/elasticsearch/snapshot-restore.md
  docs/install/docker-security.md
  docs/install/docker.md
  docs/install/helm.md
  docs/install/plugins.md
  docs/install/rpm.md
  docs/install/tar.md
  docs/install/windows.md
  docs/ism/index.md
  docs/kibana/index.md
  docs/kibana/plugins.md
  docs/security-access-control/cross-cluster-search.md
  docs/security-configuration/disable.md
  docs/upgrade/cluster-restart.md
  docs/upgrade/rolling.md
  index.md
  version-history.md
Labels: upcoming release, work in progress
