Repository opendistro/for-elasticsearch-docs, pull requests merged in 2020-07, with the labels that each got.

#262 Added common options section
  docs/elasticsearch/common-parameters.md
  docs/elasticsearch/units.md
  docs/ism/policies.md
Labels: elasticsearch

#263 Preparing for 1.9.0
  README.md
  docs/elasticsearch/snapshot-restore.md
  docs/install/deb.md
  docs/install/docker-security.md
  docs/install/docker.md
  docs/install/helm.md
  docs/install/plugins.md
  docs/install/rpm.md
  docs/install/tar.md
  docs/install/windows.md
  docs/kibana/index.md
  docs/kibana/plugins.md
  docs/security/access-control/cross-cluster-search.md
  docs/security/configuration/disable.md
  docs/upgrade/cluster-restart.md
  docs/upgrade/rolling.md
  index.md
  version-history.md
Labels: upcoming release, work in progress

#266 Basic changes for PA 1.9.0
  docs/install/deb.md
  docs/install/docker.md
  docs/install/plugins.md
  docs/install/rpm.md
  docs/install/tar.md
  docs/pa/index.md
  docs/rca/api.md
  docs/rca/index.md
  docs/rca/reference.md
Labels: upcoming release

#271 added index priority support for ISM
  docs/ism/policies.md
Labels: upcoming release
